version: "3"

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    volumes:
      - ./docker/elasticsearch/data:/usr/share/elasticsearch/data
      - ./docker/elasticsearch/logs:/usr/share/elasticsearch/logs
    ports:
      - "9200:9200"
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false

  workspace:
    build: ./docker/workspace
    # command: npm start
    volumes:
      - ./:/var/www/html
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      ELASTICSEARCH_HOST: http://elasticsearch:9200
      LISTEN: 3000
